name: clang

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Set Apple Clang 14 as the compiler
      run: |
        echo "CC=$(brew --prefix llvm@14)/bin/clang" >> "$GITHUB_ENV"
        echo "CXX=$(brew --prefix llvm@14)/bin/clang++" >> "$GITHUB_ENV"

    - name: Install Conan
      uses: turtlebrowser/get-conan@main

    - name: Configure Conan
      run: |
        conan profile new default
        cp .github/clang-14.profile ~/.conan/profiles/default
        conan profile update settings.build_type=${{env.BUILD_TYPE}} default

    - name: Install dependencies
      run: conan install . -b missing

    - name: Configure CMake
      run: cmake --preset=ci-macos

    - name: Build
      run: cmake --build build -j 2

    - name: Test
      working-directory: build
      run: ctest -j 2 --output-on-failure
